[project]
authors = ["Brad Larson <larson@sunsetlakesoftware.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
description = "MAX-CV: Accelerated image processing via MAX and Mojo"
name = "max-cv"
platforms = ["osx-arm64", "linux-aarch64", "linux-64"]
version = "0.1.0"

[tasks]
filter-single-image = { cmd="mojo package operations/ -o operations.mojopkg && python examples/filter_single_image.py", env={ MODULAR_ONLY_USE_NEW_EXTENSIBILITY_API="true" }}

[feature.test.tasks]
test = { cmd="mojo package operations/ -o operations.mojopkg && pytest", env={ MODULAR_ONLY_USE_NEW_EXTENSIBILITY_API="true" }}

[feature.test.dependencies]
pytest = ">=8.3.2, <9"

[feature.notebook.tasks]
notebook = { cmd="mojo package operations/ -o operations.mojopkg && cp operations.mojopkg examples/ && jupyter notebook", env={ MODULAR_ONLY_USE_NEW_EXTENSIBILITY_API="true" }}

[feature.notebook.dependencies]
matplotlib = ">=3.9.0,<4"
notebook = ">=7.3.2,<8"

[dependencies]
max = ">=25.1.0.dev2024122405,<26"
pillow = ">=11.0.0,<12"

[environments]
default = { solve-group = "default" }
test = { features = ["test"], solve-group = "default" }
notebook = { features = ["notebook"], solve-group = "default" }
