[project]
authors = ["Brad Larson <larson@sunsetlakesoftware.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
description = "MAX-CV: Accelerated image processing via MAX and Mojo"
name = "max-cv"
platforms = ["osx-arm64", "linux-aarch64", "linux-64"]
version = "0.1.0"

[tasks]
filter-single-image = { cmd="python examples/filter_single_image.py" }
bench = { cmd = "mojo ./benchmarks/bench.mojo"}

[feature.test.tasks]
test = { cmd = "pytest"}

[feature.test.dependencies]
pytest = ">=8.3.2, <9"

[feature.notebook.tasks]
notebook = "jupyter notebook"

[feature.notebook.dependencies]
matplotlib = ">=3.9.0,<4"
notebook = ">=7.3.2,<8"

[feature.showcase.tasks]
showcase = { cmd = "python examples/showcase.py $0"}

[feature.showcase.dependencies]
click = ">=8.1.7"
matplotlib = ">=3.9.0,<4"

[feature.showcasevideo.tasks]
showcase_video = "python examples/showcase_video.py"

[feature.showcasevideo.dependencies]
click = ">=8.1.7"
py-opencv = ">=4.11.0,<5"

[dependencies]
max = ">=25.3.0.dev2025042905,<26"
pillow = ">=11.0.0,<12"

[environments]
default = { solve-group = "default" }
test = { features = ["test"], solve-group = "default" }
notebook = { features = ["notebook"], solve-group = "default" }
showcase = { features = ["showcase"], solve-group = "default" }
showcasevideo = { features = ["showcasevideo"], solve-group = "default" }
